language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r asteroid-webservice *
  - mkdir -p deploy
  - mv asteroid-webservice.zip deploy/asteroid-webservice

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: asteroid-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로 설정
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - qudalsrnt3x@gmail.com
