server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  profiles:
    active: dev
    include:
      - aws
      - credentials

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

jwt:
  header: Authorization
  secret: asteroidChallengeHanghaeFinalProject
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

KAKAO:
  CLIENT_ID: 8ff3bc07db2d56b28fc82cb026ccd135
  REDIRECT_URL: http://localhost:8080/auth/kakao/callback
  RAW_PASSWORD: 1234
