server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  profiles:
    include:
      - aws
      - credentials

#임의로 임시 지정
jwt:
  secret: 12345678901234567890123456789012
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800


